const wordList = [
    'absolute',
    'temperature',
    'absolute zero',
    'absorption',
    'accuracy',
    'acid',
    'activation',
    'energy',
    'addition', 
    'reaction', 
    'alcohol', 
    'alkali', 
    'metal', 
    'alkaline', 
    'alkaline-earth metal', 
    'allotrope', 
    'alloy', 
    'amorphous', 
    'anhydrous', 
    'anion', 
    'aqueous solution', 
    'atom', 
    'atomic mass', 
    'atomic number', 
    'atomic theory', 
    'atomic weight',  
    'balance', 
    'base', 
    'beaker', 
    'binary compound', 
    'boil', 
    'boiling point', 
    'brittle',
    'buffer', 
    'bunsen', 
    'burner', 
    'buoyancy', 
    'calorimetry', 
    'catalyst', 
    'cation', 
    'chain reaction', 
    'charge',
]

module.exports = wordList;